### ISSUE TITLE
Tried Running it but output is not showing

### ISSUE THREAD

**Issue by ismaeli34** [artiya4u/wellmet#2]
I downloaded your code and I tried running it in my MI Redmi Note 7 Pro phone but it is not detecting any devices. I have also turned on the Bluetooth. I have attached the screenshots. Could you please help me.

![Screenshot_2020-09-04-19-47-57-281_com bootlegsoft wellmet](https://user-images.githubusercontent.com/17925504/92271356-eed4c900-eee7-11ea-9f66-55f718e8d011.jpg)
![Screenshot_2020-09-04-19-47-51-027_com bootlegsoft wellmet](https://user-images.githubusercontent.com/17925504/92271358-f1cfb980-eee7-11ea-87e8-e9500d513052.jpg)

**Comment by artiya4u** [comment]
You actually need 2 physical phones running this app near each other.
